pttrn_t1 = ["mprage", "t1", "t1w", "spgr"]

[tracer_names]
pib = ["pib"]
flute = ["flt", "flut", "flute", "flutemetamol", "ah110690", "(18f)ah110690"]
fbb = ["fbb", "florbetaben"]
fbp = ["fbp", "florbetapir"]
mk6240 = ["mk6240", "mk-6240"]

[regpars]
fwhm_t1_mni = 3
fwhm_t1 = 3
fwhm_pet = 6
costfun = "nmi"
visual = false

[dipypars]
level_iters = [10, 10, 5]
level_iters_aff = [10000, 1000, 200]
sigmas_aff = [3.0, 1.0, 0.0]

[segpars]
store_nat_gm = true
store_nat_wm = true
store_nat_csf = false
store_fwd = true
store_inv = true

[endfov_corr]
frm_rng = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
z_margin = 10

[align]
frame_min_dur = 60
decay_corr = false
reg_costfun = "nmi"
reg_fwhm = 8
reg_thrshld = 1.0
reg_metric = "adst"
sigreg_thrshld = 0.1

[align.dipy]
level_iters = [10000, 1000, 200]
sigmas = [3.0, 1.0, 0.0]

[timings]
break_time = 1800
breakdyn_t = [1200, 2400]
fulldyn_time = 3600
margin = 0.1

[timings.ur_twindow]
pib = [5400, 6600, 1200]
flute = [5400, 6600, 1200]
fbb = [5400, 6600, 1200]
fbp = [3000, 3600, 600]

[tracer]
f18 = ['fbb', 'fbp', 'flute', 'mk6240']
c11 = ['pib']